version: '3.3'

networks:
  aw-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aw-network
    ports:
      - 9090:9090
  ngrok:
    image: ngrok/ngrok:latest
    environment:
      NGROK_AUTHTOKEN: 2gTwVRFx269L4Wq04uyZkY23dcY_5MdAESCwvPXwSp8idLidd
    command: http 9090
    network_mode: host
    restart: unless-stopped

#  grafana:
#    image: grafana/grafana:latest
#    ports:
#      - 3000:3000
#    networks:
#      - aw-network
