spring:
  application:
    name: shipmonitoring
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm96920
    password: 080903
    driver-class-name: oracle.jdbc.OracleDriver

  # MySql Configs
  # datasource:
  #   url: jdbc:mysql://localhost:3306/shipdb
  #   username: root
  #   password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

external:
  api:
    url: https://external-api-clean-boarding.azurewebsites.net/api/movements
    username: rm96920
    password: 080903

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health, prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
        pushgateway:
          base-url: https://prometheus-prod-40-prod-sa-east-1.grafana.net/api/prom
          username: 1606643
          password: configured
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
